added ability to assign penalty in e-mails

diff --git a/bin/generate-mail b/bin/generate-mail
--- a/bin/generate-mail
+++ b/bin/generate-mail
@@ -4,25 +4,41 @@ TESTER_PATH=$(dirname $(readlink -f $BASH_SOURCE))
 . $TESTER_PATH/setup
 
 function usage() {
-    echo "Usage: $PROG [-h] [-s start] [-e end] assignment_nr" 1>&2;
+    echo "Usage: $PROG [-h] [-s start] [-e end] [-p penalty] -n asst_nr [GROUP_NR..]" 1>&2;
     echo "           -h: show this message" 1>&2;
-    echo "     -s start: run marker starting from group 'start'" 1>&2;
-    echo "       -e end: run marker until group 'end'" 1>&2;
-    echo "assignment_nr: run test on lab number" 1>&2
+    echo "     -s start: generate mail starting from group 'start'" 1>&2;
+    echo "       -e end: generate mail until group 'end'" 1>&2;
+	echo "   -p penalty: assign a penalty (in percentage) to GROUP_NR" 1>&2;
+    echo "   -n asst_nr: generate mail for lab number" 1>&2;
     echo "               must be 0, 1, 2 or 3" 1>&2;
+	echo "     GROUP_NR: group(s) that will receive penalty" 1>&2;
     exit 1;
 }
 
+PENALTY=20
+
 # getopts processing
-while getopts "hs:e:" ARG ; do
+while getopts "hn:s:e:p:" ARG ; do
     if [ ${ARG} = 's' ]; then
         START=$OPTARG;
         if ! [[ "$START" =~ ^[0-9]+$ ]] ; then
+            echo "Bad starting number"     
             usage;
         fi
     elif [ ${ARG} = 'e' ]; then
         END=$OPTARG;
         if ! [[ "$END" =~ ^[0-9]+$ ]] ; then
+            usage;
+        fi
+	elif [ ${ARG} = 'n' ]; then
+		NR=$OPTARG;
+		if [ $NR != "0" -a $NR != "1" -a $NR != "2" -a $NR != "3" ]; then
+                    echo "Bad assignment number: $NR" 
+                    usage;
+		fi
+	elif [ ${ARG} = 'p' ]; then
+		PENALTY=$OPTARG;
+		if ! [[ "$PENALTY" =~ ^[0-9]+$ ]] ; then
             usage;
         fi
     elif [ ${ARG} = 'h' ]; then
@@ -34,26 +50,41 @@ done
 
 shift $((OPTIND-1))
 
-if [ $# -ne 1 ]; then
+if [ -z "$NR" ]; then
+    echo "Error: please specify a lab number"
     usage;
-fi
-
-if [ $1 != "0" -a $1 != "1" -a $1 != "2" -a $1 != "3" ]; then
-    usage;
-fi
-
-NR=$1
+fi; 
 
 if [ ! -f "${ROSTER_FILE}" ]; then
 	echo "Roster file ${ROSTER_FILE} not found" 1>&2
-        exit 1
+	exit 1
 fi
 
 # remove old mbox file, if it exists
-rm -f mail-$NR.mbox
+#rm -f mail-$NR.mbox
 
 for GROUP in $(seq -f "%03g" ${START} ${END}); do
     get_marks $NR "os161-mark-${GROUP}.txt"
+	if [[ "$@" =~ $(echo $GROUP | sed 's/^0*//') ]]; then
+	echo "Applying $PENALTY% penalty to os-$GROUP"
+	MARKS=$(((MARKS * (100 - PENALTY)) / 100))
+    cat <<EOF > msg.txt
+
+Dear Group ${GROUP},
+
+Your submission for Lab $NR has been marked.
+
+"You have received $MARKS marks out of a total of $TOTAL marks."
+
+A $PENALTY% penalty has been applied due to late submission.
+
+Please see the attached files for details.
+
+Please contact $TA with any questions.
+
+ECE344 TAs
+EOF
+	else
     cat <<EOF > msg.txt
 
 Dear Group ${GROUP},
@@ -68,6 +99,7 @@ Please contact $TA with any questions.
 
 ECE344 TAs
 EOF
+	fi
     EMAILS=""
     for LOGINID in $(grep "os-${GROUP}" /etc/group | cut -d ":" -f 4 | \
         sed 's/,/ /g'); do
