major changes to tester for 2013

diff --git a/bin/os161-tester b/bin/os161-tester
--- a/bin/os161-tester
+++ b/bin/os161-tester
@@ -1,41 +1,23 @@
 #!/bin/bash
 
-# change the install path to where sys161 is installed
-INSTALL_PATH=/cad2/ece344f
+TESTER_PATH=$(dirname $(readlink -f $BASH_SOURCE))
+. $TESTER_PATH/setup
 
-BIN_PATH=${INSTALL_PATH}/cs161/bin
-TESTER_PATH=${INSTALL_PATH}/os161-tester
-# svn repo path
-SVN_REP=svn+ssh://ug131.eecg.utoronto.ca/svn
-# number of repositories, starting from 1
-NR_REPS=39
-# by default, check all assignments
-ASSIGNMENTS="0 1 2 3"
-TESTER_BIN_PATH=${TESTER_PATH}/bin
-
-# Set up the TESTER_PATH for a non-install location.
-TESTER_BIN_PATH_CANON=$(readlink -f $TESTER_BIN_PATH)
-CUR_PATH_CANON=$(dirname $(readlink -f $BASH_SOURCE))
-if [ "$TESTER_BIN_PATH_CANON" != $CUR_PATH_CANON ]; then
-    TESTER_PATH=$(readlink -f "$CUR_PATH_CANON/..")
-    echo "Tester path is $TESTER_PATH"
-fi
-
-#setup the path, making sure that our path is first
-export PATH=$BIN_PATH:/usr/local/bin:/local/bin:/usr/bin:/bin
+# Top level directory
+TOP_PATH=$TESTER_PATH/..
 
 PROG=$(basename $0)
 
 function usage() {
-    echo "Usage: $PROG [-hvVm] [-s start] [-e end] [assignment_nr]" 1>&2;
+    echo "Usage: $PROG [-hvVm] [-s start] [-e end] lab_nr" 1>&2;
     echo "           -h: show this message" 1>&2;
     echo "           -v: verbose" 1>&2;
     echo "           -V: very verbose" 1>&2;
     echo "           -m: run marker" 1>&2;
     echo "     -s start: run marker starting from group 'start'" 1>&2;
     echo "       -e end: run marker until group 'end'" 1>&2;
-    echo "assignment_nr: If not specified, then all tests are run" 1>&2
-    echo "               Otherwise, it must be 0, 1, 2 or 3" 1>&2;
+    echo "assignment_nr: run test on lab number" 1>&2
+    echo "               must be 0, 1, 2 or 3" 1>&2;
     exit 1;
 }
 
@@ -76,31 +58,21 @@ export OS161_TESTER_VERBOSE=$VERBOSE
 
 shift $((OPTIND-1))
 
-if [ $# -gt 1 ]; then
+if [ $# -ne 1 ]; then
     usage;
 fi
 
-if [ $# -eq 1 ]; then
-    if [ $1 != "0" -a $1 != "1" -a $1 != "2" -a $1 != "3" ]; then
-        usage;
-    fi
-    # check only one assignment
-    ASSIGNMENTS=$1
+if [ $1 != "0" -a $1 != "1" -a $1 != "2" -a $1 != "3" ]; then
+    usage;
 fi
 
-if [ -z "$START" ]; then
-    START=1
-fi
+NR=$1
 
-if [ -z "$END" ]; then
-    END=$NR_REPS
-fi
-    
 # run tests for a given assignment
 os161_tester() {
-    ASSIGNMENT="$1"
+    NR="$1"
     # make sure that we are in the correct OS161 root directory
-    if [ ! -f kernel ]; then
+    if [ ! -f "kernel" ]; then
         echo "$PROG: The os161 kernel executable does not exist in this directory. Run this script from the OS161 root directory." 1>&2;
         return 1;
     fi
@@ -108,109 +80,114 @@ os161_tester() {
         echo "$PROG: The os161 kernel executable in this directory is not executable. Run this script from the OS161 root directory." 1>&2;
         return 1;
     fi
-
-    if [ -e os161.log ]; then
-	    /bin/rm os161.log
+    # the testing scripts log the pexpect commands in this file
+    if [ -f "os161-pexpect.log" ]; then
+	    /bin/rm os161-pexpect.log
     fi
-
-    if [ -e os161-mark.txt ]; then
+    # the testing scripts log marks in this file
+    if [ -f "os161-mark.txt" ]; then
 	    /bin/rm os161-mark.txt
     fi
-
-    echo "Running tests for Assignment $ASSIGNMENT";
-    for test in ${TESTER_PATH}/testing-scripts/asst${ASSIGNMENT}*.py; do
+    for test in ${TOP_PATH}/scripts/asst${NR}*.py; do
         if [ -x $test ]; then
             echo "Running: $test";
             $test;
             echo
         fi
     done
-
-    if [ -e os161-mark.txt ]; then
-        awk -F "," 'BEGIN{total=0;mark=0}{total+=$2; mark+=$3}END{print "You received " mark " marks out of " total}' os161-mark.txt
+    # parse the marks file
+    if [ -f "os161-mark.txt" ]; then
+        awk -F "," 'BEGIN{total=0;mark=0}{total+=$2; mark+=$3}END{print "You received " mark " marks out of a total of " total " marks."}' os161-mark.txt
     fi
+    return 0;
 }
 
-# for students, this will dry run the marker, i.e., it will run the svn
-# checkout, build, etc., and then run the tester programs
+# this will run the marker, i.e., it will run the svn checkout, build, etc.,
+# and then run the tester programs
 os161_marker() {
-    ASSIGNMENT="$1"
+    NR="$1"
     GROUP="$2"
 
-    # remember current dir
-    echo "Checking out repo for os-${GROUP}"
-    pushd .
-
-    # create a new directory for the group
-    /bin/rm -rf os-${GROUP} && mkdir -p os-${GROUP} && cd os-${GROUP}
-
     # get the user-level programs, and apply any patches
-    tar -zxf ${TESTER_PATH}/src/os161-1.11.tar.gz && cd os161-1.11
-    for patch in ${TESTER_PATH}/src/patch.*; do
-        patch -p0 < ${patch}
+    tar -zxf ${TOP_PATH}/src/os161-1.11.tar.gz && cd os161-1.11
+    for patch in ${TOP_PATH}/src/patch.*; do
+        if [ -f "${patch}" ]; then
+            patch -p0 < ${patch}
+        fi
     done
     # remove the kern directory
     rm -rf kern
 
     # now checkout kern directory from repository
-    SVN_PATH=$SVN_REP/os-${GROUP}/svn/tags/asst${ASSIGNMENT}-end/kern
+    SVN_PATH=$SVN_REP/os-${GROUP}/svn/tags/asst${NR}-end/kern
     svn co $SVN_PATH
-
     # make sure that the checkout is successful
-    if [ $? -eq 0 ] ; then
-        # compile os161
-        BUILD_PATH=$(pwd)/../root
-
-        ./configure --ostree=$BUILD_PATH && make -s
-    
-        # configure the kernel
-        pushd kern/conf
-        ./config ASST${ASSIGNMENT}
-        popd
-    
-        # build the kernel
-        cd kern/compile/ASST${ASSIGNMENT} && make -s depend && make -s && \
-            make -s install
-
-	# setup the correct config file
-        cd $BUILD_PATH && \
-            cp ${TESTER_PATH}/sysconfig/sys161-asst${ASSIGNMENT}.conf sys161.conf
-
-        # run the tester
-        os161_tester ${ASSIGNMENT} > ../../os161-tester-${GROUP}.log
-        if [ -e "os161.log" ]; then
-	    /bin/cp os161.log ../../os161-${GROUP}.log
-        else
-            echo "os161.log not found"
-        fi
-        if [ -e "os161-mark.txt" ]; then
-	    /bin/cp os161-mark.txt ../../os161-mark-${GROUP}.txt
-        else
-            echo "os161-mark.txt not found"
-        fi
+    if [ $? -ne 0 ]; then
+        echo "svn checkout was not successful" 1>&2;
+        return 1;
     fi
 
-    # pop back to top dir
+    # compile os161
+    BUILD_PATH=$(pwd)/../root
+
+    ./configure --ostree=$BUILD_PATH && make -s
+
+    # configure the kernel
+    pushd kern/conf
+    ./config ASST${NR}
     popd
-    /bin/rm -rf os-${GROUP}
+
+    # build the kernel
+    cd kern/compile/ASST${NR} && make -s depend && make -s && \
+        make -s install
+
+    # setup the correct config file
+    cd $BUILD_PATH && \
+        cp ${TOP_PATH}/src/sys161-asst${NR}.conf sys161.conf
+
+    # run the tester
+    os161_tester ${NR} > ../../os161-tester-${GROUP}.log
+    if [ -f "os161-pexpect.log" ]; then
+        /bin/cp os161-pexpect.log ../../os161-pexpect-${GROUP}.log
+    else
+        echo "os161-pexpect.log not found" 1>&2;
+    fi
+    if [ -f "os161-mark.txt" ]; then
+        /bin/cp os161-mark.txt ../../os161-mark-${GROUP}.txt
+    else
+        echo "os161-mark.txt not found" 1>&2;
+    fi
+    return 0;
 }
 
-for i in "$ASSIGNMENTS"; do
-    if [ -z "$MARKER" ]; then
-        # run tester directly
-        os161_tester $i
-    else
-        # run the marker for each group
-        for GROUP in $(seq -f "%03g" ${START} ${END}); do
-            # do we have access to the repository?
-            # students will have access to only their repository
-            if expr "$(groups)" : ".*os-${GROUP}" > /dev/null; then
-                echo "Output being sent to os161-marker-${GROUP}.log, os161-tester-${GROUP}.log, os161-${GROUP}.log and os161-mark-${GROUP}.txt"
-                os161_marker $i $GROUP > os161-marker-${GROUP}.log 2>&1
-            fi
-        done
-    fi
-done
+echo "Running tests for Assignment $NR";
+
+if [ -z "$MARKER" ]; then
+    # run tester directly
+    echo "Output being sent to os161-pexpect.log, os161-mark.txt"
+    os161_tester $NR
+else
+    # run the marker for each group
+    for GROUP in $(seq -f "%03g" ${START} ${END}); do
+        # do we have access to the repository?
+        # students will have access to only their repository
+        if expr "$(groups)" : ".*os-${GROUP}" > /dev/null; then
+            echo -n "Output being sent to "
+            echo -n "os161-pexpect-${GROUP}.log, os161-mark-${GROUP}.txt"
+            echo "os161-tester-${GROUP}.log, os161-marker-${GROUP}.log"
+
+            # remember current dir
+            pushd .
+            # create a new directory for the group
+            /bin/rm -rf os-${GROUP} && mkdir -p os-${GROUP} && cd os-${GROUP}
+            os161_marker $NR $GROUP > ../os161-marker-${GROUP}.log 2>&1
+            # pop back to top dir
+            popd
+            /bin/rm -rf os-${GROUP}
+        fi
+    done
+fi
+
 exit 0
 
 
